yatube/about/urls.py
from django.urls import path
from . import views

app_name = "about"

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name="author"),
    path('tech/', views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('', views.index, name="index"),
    path('group/<slug:slug>/', views.group_posts, name="group_list"),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/del/', views.post_delete, name='post_delete'),
    path('search/', views.search, name='search'),
    path('posts/<int:post_id>/add_like/', views.add_like, name='like'),
    path('posts/<int:post_id>/add_dislike/', views.add_dislike, name='dislike'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'posts/<int:post_id>/<int:comment_id>/add/',
        views.add_comment_with_quote,
        name='add_comment_with_quote'
    ),
    path(
        'posts/<int:post_id>/<int:comment_id>/add_comment/',
        views.add_comment_to_comment,
        name='add_comment_to_comment'
    ),
    path(
        'posts/<int:post_id>/<int:comment_id>/del/',
        views.comment_delete,
        name='comment_del'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LogoutView, LoginView, PasswordChangeDoneView, PasswordChangeView,
    PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView,
    PasswordResetConfirmView
)
from . import views


app_name = "users"

urlpatterns = [
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='pass_change_done'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change_form.html'
    ), name='password_change'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html'
    ), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'
    ), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'
    ), name='password_reset_complete'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace="posts")),
    path('auth/', include('users.urls', namespace="users")),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace="about")),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/templates/includes/field_in_form.html
{% load user_filters %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
{% for field in form %}
  <div class="form-group my-3"
    {% if field.field.required %}
    aria-required="true"
    {% else %}
    aria-required="false"
    {% endif %}>
    <label for="{{ field.id_for_label }}">
    {{ field.label }}
    {% if field.field.required %}
    <span class="required text-danger">*</span>
    {% endif %}
    </label>
    <div>
    {{ field|addclass:'form-control' }}
    {% if field.help_text %}
    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
    {{ field.help_text|safe }}
    </small>
    {% endif %}
    </div>
  </div>
{% endfor %}

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  {% with request.resolver_match.view_name as view_name %}
  <nav id="head" class="navbar navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
        <form class="d-flex" method="GET" action="{% url 'posts:search' %}">
          <input class="form-control me-2" name=q type="text" placeholder="Поиск" aria-label="Поиск">
          <button class="btn btn-outline-success" style= "background-color: #9c9595;
                          border-color: #030303; outline-color: #545050 ; color: #030303"
          type="submit">Поиск</button>
        </form>
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'about:author' %}active_1{% endif %}"
               style="color:#030303"
               href="{% url 'about:author' %}">Об авторе</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'about:tech' %}active_1{% endif %}"
               style="color:#030303"
               href="{% url 'about:tech' %}">Технологии</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'posts:post_create' %}active_1{% endif %}"
               style="color:#030303"
               href="{% url 'posts:post_create' %}">Новая запись</a>
          </li>
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button"
                   id="dropdownMenuButton" data-bs-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                  Пользователь: {{ user.username }}
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item"
                style="color:#030303"
                href="{% url 'posts:profile' user.username %}">
                  Профиль
              </a>
              <a class="dropdown-item"
                href="{% url 'users:password_change' %}">
                  Изменить пароль
              </a>
              {% if request.user.is_superuser %}
              <a class="dropdown-item" href="{% url 'admin:index' %}">
                Админ панель
              </a>
              {% endif %}
              <div class="dropdown-divider"></div>
                <a class="dropdown-item"
                  href="{% url 'users:logout' %}">Выйти</a>
            </div>
          </div>
          {% else %}
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:login' %}active_1{% endif %}"
               style="color:#030303"
               href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:signup' %}active_1{% endif %}"
               style="color:#030303"
               href="{% url 'users:signup' %}">Регистрация</a>
          </li>
          {% endif %}
        </ul>
    </div>
  </nav>
  {% endwith %}
</header>