yatube/about/urls.py
from django.urls import path
from . import views

app_name = "about"

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name="author"),
    path('tech/', views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('', views.index, name="index"),
    path('group/<slug:slug>/', views.group_posts, name="group_list"),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/del/', views.post_delete, name='post_delete'),
    path('search/', views.search, name='search'),
    path('posts/<int:post_id>/add_like/', views.add_like, name='like'),
    path('posts/<int:post_id>/add_dislike/', views.add_dislike, name='dislike'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'posts/<int:post_id>/<int:comment_id>/add/',
        views.add_comment_with_quote,
        name='add_comment_with_quote'
    ),
    path(
        'posts/<int:post_id>/<int:comment_id>/add_comment/',
        views.add_comment_to_comment,
        name='add_comment_to_comment'
    ),
    path(
        'posts/<int:post_id>/<int:comment_id>/del/',
        views.comment_delete,
        name='comment_del'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace="posts")),
    path('auth/', include('users.urls', namespace="users")),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace="about")),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models import SET_NULL

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name="Название группы")
    slug = models.SlugField(max_length=255, unique=True, db_index=True)
    description = models.TextField(verbose_name="Описание группы")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Группа"
        verbose_name_plural = "Группы"
        ordering = ['pk', ]


class Post(models.Model):
    text = models.TextField(verbose_name="Текст",
                            help_text='Введите текст поста'
                            )
    pub_date = models.DateTimeField(default=datetime.now,
                                    verbose_name="Дата публикации"
                                    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="Автор публикации"
    )
    group = models.ForeignKey(
        Group,
        on_delete=SET_NULL,
        related_name="posts",
        blank=True,
        null=True,
        verbose_name="Группа",
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )


    def __str__(self):
        return self.text[:15]

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"
        ordering = ['-pub_date', 'pk']


class Comment(models.Model):
    hidden_text = models.TextField(
        default=None,
        blank=True,
        null=True,
        verbose_name="Цитата",
        help_text='Отредактируйте цитату при необходимости'
    )
    text = models.TextField(
        verbose_name="Текст комментария",
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        default=datetime.now,
        verbose_name="Дата комментария"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Автор комментария"
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Пост",
        help_text='Пост, к которому будет относиться комментарий'
    )
    comment_p = models.ForeignKey(
        'self',
        on_delete=SET_NULL,
        default=None,
        blank=True,
        null=True,
        related_name="comments",
        verbose_name="Комментарий",
        help_text='Комментарий, к которому будет относиться комментарий'
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"
        ordering = ['-created', 'pk']


class Follow(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name="Автор"
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name="Подписчик",
    )

    class Meta:
        verbose_name = "Подписка"
        verbose_name_plural = "Подписки"
        ordering = ['pk']
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_follow')
        ]


class Like(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="like"
    )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="author_like"
    )

    class Meta:
        constraints = (
            models.UniqueConstraint(
                fields=('post', 'user',),
                name='unique_like'
            ),
        )


class Dislike(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="dislike"
    )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="author_dislike"
    )

    class Meta:
        constraints = (
            models.UniqueConstraint(
                fields=('post', 'user',),
                name='unique_dislike'
            ),
        )

yatube/posts/forms.py
from django import forms
from django.forms import Textarea
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('hidden_text', 'text',)
        widgets = {
            'text': Textarea(attrs={'rows': 2,
                                    'placeholder': "Оставьте комментарий"}),
            'hidden_text': Textarea(attrs={'rows': 2,
                                           'style': 'background-color: #d0e2bc'})
        }

    def clean_text(self):
        if self.cleaned_data['hidden_text'] != None:
            text = self.cleaned_data['hidden_text']+self.cleaned_data['text']
            return text
        return self.cleaned_data['hidden_text']

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .forms import PostForm, CommentForm
from .models import Post, Group, User, Comment, Follow, Dislike, Like
from .decorators import post_author_only
from django.db.models import Q


POSTS_PER_PAGE = 10


def paginator_func(*args):
    paginator = Paginator(args[1], POSTS_PER_PAGE)
    page_number = args[0].GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    post_list = Post.objects.select_related('group', 'author').all()
    template = "posts/index.html"
    text = "Последние обновления на сайте:"
    page_obj = paginator_func(request, post_list)
    context = {'text': text, 'page_obj': page_obj, }
    return render(request, template, context)


def group_posts(request, slug):
    template = "posts/group_list.html"
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('author').all()
    page_obj = paginator_func(request, post_list)
    context = {'group': group, 'page_obj': page_obj}
    return HttpResponse(render(request, template, context))


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    page_obj = paginator_func(request, post_list)
    following = Follow.objects.filter(
        user__username=request.user, author=author
    )
    likes = 0
    dislikes = 0
    for post in post_list:
        likes += post.like.count()
        dislikes += post.dislike.count()
    context = {'author': author,
               'page_obj': page_obj,
               'following': following,
               'likes': likes,
               'dislikes': dislikes
    }
    return render(request, template, context, )


def post_detail(request, post_id):
    post = get_object_or_404(
        Post.objects.select_related('author', 'group'), pk=post_id
    )
    comments = post.comments.select_related('author', 'comment_p').all()

    form = CommentForm(request.POST or None)
    template = 'posts/post_detail.html'
    context = {'post': post, 'comments': comments, 'form': form }
    return render(request, template, context)


@login_required
@post_author_only
def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.delete()
    return redirect('posts:profile', post.author)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author)
    context = {'form': form}
    return render(request, template, context)


@login_required
@post_author_only
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id)

    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post
                    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {'form': form, 'is_edit': True}
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def add_comment_to_comment(request, post_id, comment_id):
    post = get_object_or_404(Post, pk=post_id)
    comment_p = get_object_or_404(Comment, pk=comment_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.comment_p = comment_p
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)

@login_required
def add_comment_with_quote(request, post_id, comment_id):
    post = get_object_or_404(Post, pk=post_id)
    comment = get_object_or_404(Comment, post=post_id, pk=comment_id)
    comments = post.comments.select_related('author').all()
    comment.hidden_text = f'<blockquote class="blockquote-2">' \
                   f'<p> {comment.text} </p> ' \
                   f'<cite> {comment.author}</cite></blockquote>'
    comment.text = None
    form = CommentForm(request.POST or None, instance=comment)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect('posts:post_detail', post_id=post_id)
    template = 'posts/post_detail.html'
    context = {'form': form, 'post': post, 'comments': comments, 'not_hidden': True}
    return render(request, template, context)


@login_required
def comment_delete(request, post_id, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    return redirect(request.META.get('HTTP_REFERER',
                                     'redirect_if_referer_not_found'))


@login_required
def follow_index(request):
    template = "posts/follow.html"
    post_list = Post.objects.select_related('group', 'author').filter(
        author__following__user=request.user
    )
    page_obj = paginator_func(request, post_list)
    context = {"page_obj": page_obj}
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect("posts:profile", username)


@login_required
def profile_unfollow(request, username):
    get_object_or_404(Follow, user=request.user,
                      author__username=username).delete()
    return redirect("posts:profile", username)


def search(request):
    template = 'posts/search.html'
    if request.method == 'GET' and request.GET['q']:
        query = request.GET.get('q')
        query_q = f'?q={query}'
        search_list = Post.objects.select_related('group', 'author').filter(
            Q(text__iregex=query) |
            Q(group__title__iregex=query) |
            Q(author__first_name__iregex=query) |
            Q(author__last_name__iregex=query) |
            Q(author__username__iregex=query)
        )
        page_obj = paginator_func(request, search_list)
        context = {
            'page_obj': page_obj,
            'query': query,
            'query_q': query_q,
        }
        return render(request, template, context)
    return render(request, template)


@login_required
@login_required
def add_like(request, post_id):
    try:
        dislike = Dislike.objects.get(post_id=post_id, user=request.user)
        dislike.delete()
        Like.objects.create(user=request.user, post_id=post_id)
    except Dislike.DoesNotExist:
        try:
            like = Like.objects.get(post_id=post_id, user=request.user)
            like.delete()
        except Like.DoesNotExist:
            Like.objects.create(user=request.user, post_id=post_id)
    return redirect(request.META.get('HTTP_REFERER',
                                     'redirect_if_referer_not_found'))


@login_required
def add_dislike(request, post_id):
    try:
        like = Like.objects.get(post_id=post_id, user=request.user)
        like.delete()
        Dislike.objects.create(user=request.user, post_id=post_id)
    except Like.DoesNotExist:
        try:
            dislike = Dislike.objects.get(
                post_id=post_id, user=request.user
            )
            dislike.delete()
        except Dislike.DoesNotExist:
            Dislike.objects.create(user=request.user, post_id=post_id)
    return redirect(request.META.get('HTTP_REFERER',
                                     'redirect_if_referer_not_found'))

yatube/templates/posts/includes/author_view.html
  <a href="{% url 'posts:profile' post.author.username %}">
    {% if post.author.get_full_name %}
      {{ post.author.get_full_name }}
    {% else %}
      {{ post.author.username }}
    {% endif %}
    {% if post.author == request.user %}
      <span style="color:red">(Вы)</span>
    {% endif %}
  </a>

yatube/templates/posts/includes/comment_view.html
{% load user_filters %}
    <h5 class="mt-0">
      <a href="{% url 'posts:profile' comment.author.username %}">
        {% include 'posts/includes/author_view.html' with post=comment %}
      </a>
    </h5>
    <p style="font:menu; color:grey">
      {{ comment.created }}</p>
    <p>
      {{ comment.text|safe|linebreaksbr }}
    </p>
    {% if global_comment %}
    {% if comment.comments.count %}
    <a data-bs-toggle="collapse"
       href="#collapseComment{{comment.pk}}" aria-expanded="false"
       aria-controls="collapseComments">
      <span style="font:menu">Развернуть ответы ({{ comment.comments.count }})</span>
    </a>
    {% endif %}
    <a data-bs-toggle="collapse"
       href="#collapse{{comment.pk}}" aria-expanded="false"
       aria-controls="collapseExample">
      <span style="font:menu">Ответить</span>
    </a>
    <div class="collapse" id="collapse{{comment.pk}}">
      <div class="card card-body">
        <form method="post"
              action="{% url 'posts:add_comment_to_comment' post.id comment.id %}">
          {% csrf_token %}
          <div class="form-group mb-2">
            {{ form.text|addclass:'form-control' }}
          </div>
          <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
      </div>
    </div>
    <a href="{% url 'posts:add_comment_with_quote' post.id comment.id %}">
      <span style="font:menu">Процитировать</span>
    </a>
    {% endif %}
    {% if comment.author.username == request.user.username or request.user.is_superuser %}
    <a href="{% url 'posts:comment_del' post.id comment.id %}"
       style="float: right;">
      <span style="color:red; font:menu">Удалить комментарий</span>
    </a>
    {% endif %}

yatube/templates/posts/includes/form.errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="{{ query_q }}{{ simbol }}page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="{{ query_q }}{{ simbol }}page{{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="{{ query_q }}{{ simbol }}page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="{{ query_q }}{{ simbol }}page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="{{ query_q }}{{ simbol }}&page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

yatube/templates/posts/includes/post_view.html
{% load thumbnail %}
<ul>
  <li>
    Автор:
    {% include 'posts/includes/author_view.html' %}
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
</ul>
{% thumbnail post.image "960x500" crop="center" upscale=True as im %}
  <img class="card-img my-2" src="{{ im.url }}">
{% endthumbnail %}
<p>{{ post.text }}</p>
  <div>
    <b>Количество комментариев:</b>
    <a href="{% url 'posts:post_detail' post.pk %}">
        {{ post.comments.count }}
    </a>
  </div>
<br>
<a class="btn btn-outline-primary btn-sm"
   href="{% url 'posts:post_detail' post.pk %}"
   role="button">
    Подробная информация
</a>
{% if template_index %}
{% if post.group %}
  <a class="btn btn-outline-primary btn-sm"
     href="{% url 'posts:group_list' post.group.slug %}">
    Все записи группы
  </a>
{% endif %}
{% endif %}
<div>
<a href="{% url 'posts:like' post.id %}" style="color:green">
  👍 +{{ post.like.count }}
</a>
<a href="{% url 'posts:dislike' post.id %}" style="color:red">
  👎 -{{ post.dislike.count }}
</a>
</div>
{% if not forloop.last %}<hr>{% endif %}

yatube/templates/posts/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}