yatube/about/urls.py
from django.urls import path
from . import views

app_name = "about"

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name="author"),
    path('tech/', views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('', views.index, name="index"),
    path('group/<slug:slug>/', views.group_posts, name="group_list"),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/del/', views.post_delete, name='post_delete'),
    path('search/', views.search, name='search'),
    path('posts/<int:post_id>/add_like/', views.add_like, name='like'),
    path('posts/<int:post_id>/add_dislike/', views.add_dislike, name='dislike'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'posts/<int:post_id>/<int:comment_id>/add/',
        views.add_comment_with_quote,
        name='add_comment_with_quote'
    ),
    path(
        'posts/<int:post_id>/<int:comment_id>/add_comment/',
        views.add_comment_to_comment,
        name='add_comment_to_comment'
    ),
    path(
        'posts/<int:post_id>/<int:comment_id>/del/',
        views.comment_delete,
        name='comment_del'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LogoutView, LoginView, PasswordChangeDoneView, PasswordChangeView,
    PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView,
    PasswordResetConfirmView
)
from . import views


app_name = "users"

urlpatterns = [
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='pass_change_done'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change_form.html'
    ), name='password_change'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html'
    ), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'
    ), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'
    ), name='password_reset_complete'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace="posts")),
    path('auth/', include('users.urls', namespace="users")),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace="about")),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from posts.models import User


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import AccessMixin
from django.shortcuts import redirect
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(AccessMixin, CreateView):
    form_class = CreationForm
    template_name = 'users/signup.html'
    success_url = reverse_lazy('posts:index')

    def form_valid(self, form):
        """функция автоматического залогинивания при регистрации
        нового юзера"""
        form.save()
        username = self.request.POST['username']
        password = self.request.POST['password1']
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return redirect('posts:index')

    def dispatch(self, request, *args, **kwargs):
        """функция перенаправляет авторизованного пользователя при попытке
        регистрации"""
        if request.user.is_authenticated:
            return redirect('posts:index')
        return super().dispatch(request, *args, **kwargs)

yatube/templates/users/logged_out.html
{% extends "base.html" %}
{% block title %}<title>Выход из учетной записи</title>{% endblock %}
{% block content %}
{% include 'users/includes/template_class_top.html' %}
  <div class="card-header">Выход</div>
    <div class="card-body">
      <p>Вы вышли из своей учётной записи. Ждём вас снова!</p>
    </div>
  </div>
{% include 'users/includes/template_class_foot.html' %}
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}<title>Войти</title>{% endblock %}
{% block content %}
{% load user_filters %}
{% include 'users/includes/template_class_top.html' %}
  <div class="card-header">
    Войти на сайт
  </div>
  <div class="card-body">
    {% include 'posts/includes/form.errors.html' %}
    <form method="post" action="#">
      {% csrf_token %}
      <div class="form-group row my-3">
        <label for="id_username">
          Имя пользователя
          <span class="required text-danger">*</span>
        </label>
        <input type="text" name="username" autofocus class="form-control" required id="id_username">
      </div>
      <div class="form-group row my-3">
        <label for="id_password">
          Пароль
          <span class="required text-danger">*</span>
        </label>
        <input type="password" name="password" class="form-control" required id="id_password">
      </div>
      <div class="col-md-6 offset-md-4">
        <button type="submit" class="btn btn-primary">
          Войти
        </button>
        <a href="{% url 'users:password_reset' %}" class="btn btn-link">
          Забыли пароль?
        </a>
      </div>
    </form>
  </div>
{% include 'users/includes/template_class_foot.html' %}
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}<title>Смена пароля прошла успешно!</title>{% endblock %}
{% block content %}
{% include 'users/includes/template_class_top.html' %}
  <div class="card-header">
    Форма смены пароля:
  </div>
  <div class="card-body">
    <p>Пароль успешно изменен.</p>
      <a href="{% url 'posts:index' %}" class="btn btn-link">
        На главную
      </a>
  </div> <!-- card body -->
{% include 'users/includes/template_class_foot.html' %}
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}<title>Смена пароля</title>{% endblock %}
{% block content %}
{% include 'users/includes/template_class_top.html' %}
  <div class="card-header">
    Изменить пароль
  </div>
  <div class="card-body">
    <form method="post" action="#">
      {% csrf_token %}
      <div class="form-group row my-3 p-3">
        <label for="id_old_password">
          Старый пароль
          <span class="required text-danger">*</span>
        </label>
        <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
      </div>
      <div class="form-group row my-3 p-3">
        <label for="id_new_password1">
          Новый пароль
          <span class="required text-danger">*</span>
        </label>
        <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
        <small id="id_new_password1-help" class="form-text text-muted">
          <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
        </small>
      </div>
      <div class="form-group row my-3 p-3">
        <label for="id_new_password2">
          Подтверждение нового пароля
          <span class="required text-danger">*</span>
        </label>
        <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
      </div>
      <div class="col-md-6 offset-md-4">
        <button type="submit" class="btn btn-primary">
          Изменить пароль
        </button>
      </div>
    </form>
  </div> <!-- card body -->
{% include 'users/includes/template_class_foot.html' %}
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}<title>Восстановление пароля</title>{% endblock %}
{% block content %}
{% include 'users/includes/template_class_top.html' %}
  <div class="card-header">
    Восстановление пароля завершено
  </div>
  <div class="card-body">
    <p>Ваш пароль был сохранен. Используйте его для входа</p>
    <a href="{% url 'users:login' %}">Войти</a>
  </div>
{% include 'users/includes/template_class_foot.html' %}
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}<title>Смена пароля</title>{% endblock %}
{% block content %}
{% if validlink %}
{% include 'users/includes/template_class_top.html' %}
  <div class="card-header">
    Введите новый пароль
  </div>
  <div class="card-body">
    <form method="post" action="#">
      {% csrf_token %}
      <div class="form-group row my-3 p-3">
        <label for="id_new_password1">
          Новый пароль
          <span class="required text-danger">*</span>
        </label>
        <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
        <small id="id_new_password1-help" class="form-text text-muted">
          <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
        </small>
      </div>
      <div class="form-group row my-3 p-3">
        <label for="id_new_password2">
          Подтверждение нового пароля
          <span class="required text-danger">*</span>
        </label>
        <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
      </div>
      <div class="col-md-6 offset-md-4">
        <button type="submit" class="btn btn-primary">
          Назначить новый пароль
        </button>
      </div>
    </form>
  </div>
{% include 'users/include.template_class_foot' %}
{% else %}
  <div class="card-header">
    Ошибка
  </div>
  <div class="card-body">
    <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
  </div>
{% include 'users/includes/template_class_foot.html' %}
{% endif %}
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}<title>Сброс пароля</title>{% endblock %}
{% block content %}
{% include 'users/includes/template_class_top.html' %}
  <div class="card-header">
    Отправлено письмо
  </div>
  <div class="card-body">
    <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
  </div>
{% include 'users/includes/template_class_foot.html' %}
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}<title>Сброс пароля</title>{% endblock %}
{% block content %}
{% include 'users/includes/template_class_top.html' %}
  <div class="card-header">
    Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
  </div>
  <div class="card-body">
    <form method="post" action="#">
      {% csrf_token %}
      <div class="form-group row my-3 p-3">
        <label for="id_email">
          Адрес электронной почты
          <span class="required text-danger">*</span>
        </label>
        <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
      </div>
      <div class="col-md-6 offset-md-4">
        <button type="submit" class="btn btn-primary">
          Сбросить пароль
        </button>
      </div>
    </form>
  </div>
{% include 'users/includes/template_class_foot.html' %}
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}<title>Зарегистрироваться</title>{% endblock %}
{% block content %}
{% include 'users/includes/template_class_top.html' %}
  <div class="card-header">Зарегистрироваться</div>
    <div class="card-body">
      {% load user_filters %}
      {% if form.errors %}
      {% for field in form %}
      {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
      {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
      {% endfor %}
      {% endif %}
      <form method="post" action="{% url 'users:signup' %}">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group row my-3">
          <label for="{{ field.id_for_label }}">
            {{ field.label }}
            {% if field.field.required %}
            <span class="required text-danger">*</span>
            {% endif %}
          </label>
          {{ field|addclass:'form-control' }}
          {% if field.help_text %}
          <small
              id="{{ field.id_for_label }}-help"
              class="form-text text-muted"
          >
            {{ field.help_text|safe }}
          </small>
          {% endif %}
        </div>
        {% endfor %}
        <div class="col-md-6 offset-md-4">
          <button type="submit" class="btn btn-primary">
            Зарегистрироваться
          </button>
        </div>
      </form>
    </div>
{% include 'users/includes/template_class_foot.html' %}
{% endblock %} 